### PR TITLE
FIX: Handle root path correctly

### LINKED ISSUE #3353: Root `Path` is incorrectly handled in ScalaJS
fs2 version: `3.9.3`

Reproduction example:
```scala
import fs2.io.file.Path

val p = Path("/")
println(p.normalize.absolute)
```
Outputs current working directory instead of `/` when run in JS.

Happens because of this code:
https://github.com/typelevel/fs2/blob/53f458d6ac4044df2b8e2d4310b92a1fb8953d80/io/js/src/main/scala/fs2/io/file/Path.scala#L102-L105

### PR DESCRIPTION
**Pull request by InversionSpaces**
Drop trailing separators in `Path` creation only if it is not the only thing in the path.

Fixes #3353

### CODE REVIEW

File: io/js/src/main/scala/fs2/io/file/Path.scala [hunk 1]
```diff
@@ -98,9 +98,21 @@ final case class Path private[file] (override val toString: String) extends Path
...
+  /*
+   * NOTE: It seems like scala js does not rewrite this to a loop?
+   * Call stack limit is reached if there are too many separators.
+   */
+  @tailrec
+  private[file] def dropTrailingSep(path: String): String =
+    // Drop separator only if there is something else left
+    if (path.endsWith(sep) && path.length > sep.length)
+      dropTrailingSep(path.dropRight(sep.length))
+    else path
```
Comment (armanbilge) [inline io/js/src/main/scala/fs2/io/file/Path.scala:110]: It does actually 🤔  Here's what it's compiled to:

```js
$c_Lfs2_io_file_Path$.prototype.dropTrailingSep__T__T = (function(path) {
  while (true) {
    if ($f_T__endsWith__T__Z($n(path), this.Lfs2_io_file_Path$__f_sep)) {
      var this$1 = $n(path);
      var this$2 = $n(this.Lfs2_io_file_Path$__f_sep);
      var $$x2 = (this$1.length > this$2.length)
    } else {
      var $$x2 = false
    };
    if ($$x2) {
      var $$x1 = $m_sc_StringOps$();
      var x = path;
      var this$4 = $n(this.Lfs2_io_file_Path$__f_sep);
      path = $n($$x1).dropRight$extension__T__I__T(x, this$4.length)
    } else {
      break
    }
  };
  return path
});
```

Comment (armanbilge) [reply io/js/src/main/scala/fs2/io/file/Path.scala:110]: This passes for me. How were you getting the failure?
```scala
assertEquals(Path("/".repeat(Int.MaxValue/8)), Path("/"))
```

File: io/shared/src/test/scala/fs2/io/file/PathSuite.scala [hunk 2]
```diff
@@ -44,6 +44,20 @@ class PathSuite extends Fs2IoSuite {
   test("construction") {
     assertEquals(Path("foo/bar"), Path("foo") / "bar")
     assertEquals(Path("/foo/bar"), Path("/foo") / "bar")
+    forAll((sepLength: Int) =>
+      if (sepLength >= 0 && sepLength <= 100)
```
Comment (armanbilge) [inline io/shared/src/test/scala/fs2/io/file/PathSuite.scala:48]: These `if` guards are probably skipping most/all of the generated values. Instead you should do something like this.
```suggestion
    forAll(Gen.choose(0, 100))((sepLength: Int) =>
```

File: io/js/src/main/scala/fs2/io/file/Path.scala [hunk 3]
```diff
@@ -98,9 +98,21 @@ final case class Path private[file] (override val toString: String) extends Path
...
   private[file] val sep = facade.path.sep
 
+  /*
+   * NOTE: It seems like scala js does not rewrite this to a loop?
+   * Call stack limit is reached if there are too many separators.
+   */
+  @tailrec
+  private[file] def dropTrailingSep(path: String): String =
+    // Drop separator only if there is something else left
+    if (path.endsWith(sep) && path.length > sep.length)
```
Comment (armanbilge) [inline io/js/src/main/scala/fs2/io/file/Path.scala:108]: I don't like to Officially:tm: support Windows 🤮 but its path can look like `C:\` which I think would get re-written to `C:`. I have no idea if that's good or bad 😅

Comment (BalmungSan) [reply io/js/src/main/scala/fs2/io/file/Path.scala:108]: Doing some tests on **Powershell**

```
PS C:\Users\PC> cd c:
PS C:\Users\PC> cd C:
PS C:\Users\PC> cd C:\
PS C:\>
```

File: io/js/src/main/scala/fs2/io/file/Path.scala (hunk 1 above)
Comment (InversionSpaces) [reply io/js/src/main/scala/fs2/io/file/Path.scala]: Strange, I wrote this comment when I used `IndexedSeqView` instead of `String`.

File: io/js/src/main/scala/fs2/io/file/Path.scala (hunk 3 above)
Comment (InversionSpaces) [reply io/js/src/main/scala/fs2/io/file/Path.scala]: Used node API exclusively

File: io/shared/src/test/scala/fs2/io/file/PathSuite.scala [hunk 4]
```diff
@@ -38,12 +38,31 @@ class PathSuite extends Fs2IoSuite {
...
     assertEquals(Path("/foo/bar"), Path("/foo") / "bar")
+
+    val sepLengthGen = Gen.choose(0, 1024)
+
+    forAll(sepLengthGen)((sepLength: Int) =>
+      assertEquals(
+        Path("/".repeat(sepLength)).toString,
+        "/"
+      )
+    )
```
Comment (armanbilge) [inline io/shared/src/test/scala/fs2/io/file/PathSuite.scala:59]: Wait a minute, is this test passing even when `sepLength = 0`?

Comment (InversionSpaces) [reply io/shared/src/test/scala/fs2/io/file/PathSuite.scala]: No, it should not. After investigation I found out that scalacheck is mishandled in this suite. Tried to fix that

**Review by armanbilge — APPROVED** [review]
thank you!
