### PR TITLE
fix socket option  for tcp server

### LINKED ISSUE #2414: Cannot set tcp keep_alive to server
Currently scoket options are set to the `AsynchronousSeverSocketChannel` but it should  be applied to the accepted `AsynchronousSocketChannel`,  `AsynchronousSeverSocketChannel` cannot set keep_alive, actually

### PR DESCRIPTION
**Pull request by jilen**
Fixes #2414

### CODE REVIEW

File: io/src/main/scala/fs2/io/net/SocketGroup.scala [hunk 1]
```diff
@@ -97,9 +97,11 @@ private[net] object SocketGroup {
...
           val ch =
             AsynchronousChannelProvider.provider.openAsynchronousSocketChannel(channelGroup)
-          options.foreach(opt => ch.setOption(opt.key, opt.value))
-          ch
-        }
+          Either
+            .catchNonFatal(options.foreach(opt => ch.setOption(opt.key, opt.value)))
+            .liftTo[F]
+            .as(ch)
+        }.flatten
```
Comment (vasilmkd) [inline io/src/main/scala/fs2/io/net/SocketGroup.scala:104]: You could probably use `Async[F].defer` for this whole block.

File: io/src/main/scala/fs2/io/net/SocketGroup.scala [hunk 2]
```diff
@@ -94,11 +94,13 @@ private[net] object SocketGroup {
...
     ): Resource[F, Socket[F]] = {
       def setup: F[AsynchronousSocketChannel] =
-        Async[F].delay {
+        Async[F].defer {
           val ch =
             AsynchronousChannelProvider.provider.openAsynchronousSocketChannel(channelGroup)
-          options.foreach(opt => ch.setOption(opt.key, opt.value))
-          ch
+          Either
+            .catchNonFatal(options.foreach(opt => ch.setOption(opt.key, opt.value)))
```
Comment (mpilquist) [inline io/src/main/scala/fs2/io/net/SocketGroup.scala:101]: Hm, why is this `catchNonFatal` necessary? The old code would still result in any exception getting thrown from `ch.setOption` failing the overall effect.

**Review by jilen — COMMENTED** [review]
Confirmed delay is safe for exception handling

**Review by mpilquist — APPROVED** [review]
