### PR TITLE
Fix for interruption skipping error handlers in certain cases

### LINKED ISSUE #2197: Errors are not always catched with .handleErrorWith
Take a look at https://github.com/nikiforo/fs-handle/pull/1
The example is minimized, but can be minimized even further.

A way to reproduce.
On one tab launch the client `sbt runMain name.nikiforo.Client`
On the other tab launch the server
```
sbt
> runMain name.nikiforo.Server
acquired localhost 20111
got 0 messages
```
Wait a minute
```
<...>
got 538 messages
got 485 messages
exception handling socket Connection reset
got 320 messages
exception handling socket Connection reset
<...>
got 1 messages
DISASTER: Multiple exceptions were thrown (45), first java.io.IOException: Connection reset
```

Despite some errors being catched at https://github.com/nikiforo/fs-handle/pull/1/files#diff-3e571cc6ca077b3bd8dc2bde7f5f8e9787724d1f98e64d56a34e7b263957bfd5R47 others propagate to the encompassing stream, halt it, are catched only at https://github.com/nikiforo/fs-handle/pull/1/files#diff-4a1eb1d4e3714fb61d4adc5f666a0a5c435065c20bfd0433f08697a0a2c96715R27

At this point I want to differentiate whether or not the provided behavior is expected.

@mpilquist

### PR DESCRIPTION
**Pull request by mpilquist**
Fixes #2197

Based on the analysis from @RaasAhsan. All tests pass with this change and while it feels pretty adhoc, I think we should fix this in the simplest way possible and then look at revamping stream interruption in general later.

### CODE REVIEW

File: core/shared/src/test/scala/fs2/StreamConcurrentlySuite.scala [hunk 1]
```diff
@@ -149,4 +149,24 @@ class StreamConcurrentlySuite extends Fs2Suite {
     }
   }
 
+  test("bug 2197".only) {
```
Comment (SystemFw) [inline core/shared/src/test/scala/fs2/StreamConcurrentlySuite.scala:152]: leftover

**Review by SystemFw — COMMENTED** [review]
I think we'd have to leave with the ad-hoc nature of this for now, as you say

**Review by diesalbla — APPROVED** [review]
