### PR TITLE
`PipedStreamBuffer` circular copying overflow fix

### LINKED ISSUE #2637: ArrayIndexOutOfBoundsException using fs2.io.writeOutputStream when number of bytes exceeds Int.MaxValue
When attempting to write more than `Int.MaxValue` bytes to an `OutputStream` using `fs2.io.writeOutputStream`, I get an `ArrayIndexOutOfBoundsException` with the stack trace pointing at [`fs2.io.internal.PipedStreamBuffer$$anon$2.circularWrite(PipedStreamBuffer.scala:374)`](https://github.com/typelevel/fs2/blob/v3.1.3/io/jvm/src/main/scala/fs2/io/internal/PipedStreamBuffer.scala#L374).

I'm able to reproduce this on both v2.5.9 and v3.1.3 using the code in this repository: https://github.com/mrdziuban/fs2-writeOutputStream. The code in each `Test.scala` file tries to write a total of 2,160,000,000 bytes to an `OutputStream` that's being read by `fs2.io.readOutputStream`.

The full stack traces are:

<details><summary>v2.x stack trace</summary>

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
  at java.lang.System.arraycopy(Native Method)
  at fs2.io.internal.PipedStreamBuffer$$anon$2.circularWrite(PipedStreamBuffer.scala:374)
  at fs2.io.internal.PipedStreamBuffer$$anon$2.write(PipedStreamBuffer.scala:302)
  at java.io.OutputStream.write(OutputStream.java:75)
  at fs2.io.package$.$anonfun$writeOutputStream$3(io.scala:136)
  at unsafeRunSync @ example.Test$.main(Test.scala:26)
  at delay$extension @ fs2.io.package$.$anonfun$readOutputStream$2(io.scala:165)
  at map @ fs2.internal.CompileScope.interruptibleEval(CompileScope.scala:413)
  at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:503)
  at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
  at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
  at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
  at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
  at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
  at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
  at flatMap @ fs2.internal.FreeC$.$anonfun$compile$7(Algebra.scala:463)
  at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:460)
  at flatMap @ fs2.internal.FreeC$.outerLoop$1(Algebra.scala:595)
  at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
  at unsafeRunSync @ example.Test$.main(Test.scala:26)
```

</details>

<details><summary>v3.x stack trace</summary>

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
  at java.lang.System.arraycopy(Native Method)
  at fs2.io.internal.PipedStreamBuffer$$anon$2.circularWrite(PipedStreamBuffer.scala:374)
  at fs2.io.internal.PipedStreamBuffer$$anon$2.write(PipedStreamBuffer.scala:302)
  at java.io.OutputStream.write(OutputStream.java:75)
  at fs2.io.package$.$anonfun$writeOutputStream$3(io.scala:111)
  at blocking @ fs2.io.package$.$anonfun$writeOutputStream$2(io.scala:111)
  at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152
  at handleErrorWith @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.handleErrorWith(Compiler.scala:150)
  at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152
  at flatMap @ fs2.Pull$.goEval$1(Pull.scala:1035)
  at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:904)
  at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:904)
  at flatMap @ fs2.Pull$.fs2$Pull$$interruptGuard$1(Pull.scala:904)
  at flatMap @ fs2.Pull$.$anonfun$compile$26(Pull.scala:1197)
  at >>$extension @ fs2.Pull$.goFlatMapOut$1(Pull.scala:990)
  at >>$extension @ fs2.Pull$.goFlatMapOut$1(Pull.scala:990)
  at blocking @ fs2.io.package$.$anonfun$writeOutputStream$2(io.scala:111)
  at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152
  at handleErrorWith @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.handleErrorWith(Compiler.scala:150)
  at flatMap @ fs2.Compiler$TargetLowPriority$MonadErrorTarget.flatMap(Compiler.scala:152
  at flatMap @ fs2.Pull$.goEval$1(Pull.scala:1035)
```

</details>

This issue seems to be related to #2457 and the subsequent fixes #2458 and #2459.

### PR DESCRIPTION
**Pull request by vasilmkd**
Resolves #2637.

The built in `%` remainder operator can return a negative result. We're actually interested in the modulus operation which returns a non-negative result.

### CODE REVIEW

File: io/jvm/src/main/scala/fs2/io/internal/PipedStreamBuffer.scala [hunk 1]
```diff
@@ -364,15 +364,35 @@ private[io] final class PipedStreamBuffer(private[this] val capacity: Int) { sel
...
+    * numbers. This method always returns a non-negative result.
+    *
+    * @param n the divident
+    * @param m the divisor
+    * @return the result of `n` modulo `m`
+    */
+  private[this] def modulus(n: Int, m: Int): Int = {
+    val r = n % m
+    if (r < 0) r + m else r
+  }
```
Comment (armanbilge) [inline io/jvm/src/main/scala/fs2/io/internal/PipedStreamBuffer.scala:397]: Can this be replaced with `lang.Integer.remainderUnsigned`?
https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#remainderUnsigned-int-int-

Comment (vasilmkd) [reply io/jvm/src/main/scala/fs2/io/internal/PipedStreamBuffer.scala]: That worked. Thanks.
