### PR TITLE
Fixing interruption behaviour

### LINKED ISSUE #3169: groupWithin: inconsistent behaviour on source termination
### [scastie](https://scastie.scala-lang.org/HAeMqP3BTXSUBGuf2eqPMg)

While playing around with a new implementation of groupWithin I discovered a bug. The combinator doesn't handle upstream termination consistently. See below

```scala
    val finiteStream = Stream
      .range(0, 4)
      .covary[IO]
      .metered(1.second)

    val doesNotTerminate = 
        finiteStream
          .groupWithin(Int.MaxValue, 2.days) 
          .evalTap(IO.println)
          .compile
          .lastOrError.void

    val terminates =
         finiteStream
          .groupWithin(8, 2.days)
          .evalTap(IO.println)
          .compile
          .lastOrError.void
```

I have an idea why this is happening. I'm happy to take a look 💪🏾 

The question I have though is: what's the correct behaviour here ?
 - terminating the stream when upstream terminates 
 - keeping the stream alive

### PR DESCRIPTION
**Pull request by Angel-O**
## Summary

- Fixes #3169
- Adding missing tests around error/interruption propagation
- Adding stress/integrity test

## Changes

increasing supply by `Int.MaxValue + chunkSize` on upstream `finalization` to prevent the supply semaphore from blocking when upstream is interrupted while downstream is waiting for the timeout to expire or to have enough elements

## Notes

- the `stress test: all elements are processed` test is nothing but a copy of the benchmark with and integrity check at the end. While it may seem redundant (i.e. `should never lose any elements` should cover it), in reality it is possible to write an [implementation](https://github.com/typelevel/fs2/pull/3162) that passes that test but fails this one. (~on a side note, that explains the big performance gain of the implementation linked earlier, so~ having this test in place could prevent being misled when looking at benchmark results, while working on a new implementation 🙏🏾 )

### CODE REVIEW

**Comment by armanbilge** [comment]
How does this PR relate to https://github.com/typelevel/fs2/pull/3186? Should this be reviewed first?

**Comment by Angel-O** [comment]
I ended up making all the changes in #3186, since I wanted to verify the correctness of that implementation, but I'm happy for this one to be considered first. I'll sync up the branch, run `sbt prePR` and push again if needed.

File: core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala [hunk 1]
```diff
@@ -834,6 +835,77 @@ class StreamCombinatorsSuite extends Fs2Suite {
...
+        case object SevenNotAllowed extends NoStackTrace
+
+        val source = Stream
+          .iterate(0)(_ + 1)
+          .covary[IO]
+          .evalTap(n => IO.raiseError(SevenNotAllowed).whenA(n == 7))
+
+        val downstream = source.groupWithin(100, 2.seconds)
+
+        downstream.intercept[SevenNotAllowed.type]
```
Comment (armanbilge) [inline core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala:850]: Should we make an assertion here about what the downstream has / has not received before the error?

File: core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala [hunk 2]
```diff
@@ -834,6 +835,77 @@ class StreamCombinatorsSuite extends Fs2Suite {
...
+              // specified, unless source ends, due to interruption or
+              // natural termination (i.e runs out of elements)
+              val downstream: Stream[IO, Chunk[Int]] =
+                source.groupWithin(Int.MaxValue, 1.day)
+
+              downstream.compile.lastOrError
+                .map(_.toList)
+                .timeout(downstreamTimeout)
+                .flatTap(_ => IO.monotonic.flatMap(ref.set))
+                .flatMap(emit => ref.get.map(timeLapsed => (timeLapsed, emit)))
```
Comment (armanbilge) [inline core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala:883]:
```suggestion
                .timed
```

File: core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala [hunk 3]
```diff
@@ -874,6 +874,7 @@ class StreamCombinatorsSuite extends Fs2Suite {
             source.groupWithin(Int.MaxValue, 1.day)
 
           downstream.compile.lastOrError
+            .timeout(downstreamTimeout)
```
Comment (armanbilge) [inline core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala:877]: Why is this timeout necessary? Since its an `executeEmbed` test.

File: core/shared/src/main/scala/fs2/Stream.scala [hunk 4]
```diff
@@ -1471,7 +1471,9 @@ final class Stream[+F[_], +O] private[fs2] (private[fs2] val underlying: Pull[F,
         }
 
         def endSupply(result: Either[Throwable, Unit]): F2[Unit] =
-          buffer.update(_.copy(endOfSupply = Some(result))) *> supply.releaseN(Int.MaxValue)
+          buffer.update(_.copy(endOfSupply = Some(result))) *> supply.releaseN(
+            Int.MaxValue + outputLong
+          )
```
Comment (armanbilge) [inline core/shared/src/main/scala/fs2/Stream.scala:1476]: Sorry, dumb question: why is `Int.MaxValue` a "magic number" in this context? I would have thought it's effectively maxing out the semaphore, but if it needs `+ outputLong` to work then I feel like it must have more significance?

Comment (Angel-O) [reply core/shared/src/main/scala/fs2/Stream.scala:1476]: Legit question to be fair. Had to think about it again.

Interruption of the upstream fiber (i.e. Outcome.Cancelled) is handled  downstream by doing nothing (permits are never released)
So by increasing the supply to `Int.MaxValue` we are just evening out the negative balance (`Int.MaxValue` is to account for the worst case scenario: at most the `chunkSize` parameter will be equal to `Int.MaxValue`)

```scala
    val waitSupply = supply.acquireN(outputLong).guaranteeCase {
        case Outcome.Succeeded(_) => supply.releaseN(outputLong)
        case _                    => F.unit
     }
```

Now after getting past the "checkpoint"  above we are acquiring `outputLong` permits again

```scala
    acq <- F.race(F.sleep(timeout), waitSupply).flatMap {
      case Left(_)  => onTimeout
      case Right(_) => supply.acquireN(outputLong).as(outputLong)
    }
```

So in order to get past this point we need to release an additional `outputLong` permits and that allows the stream to be unblocked

Comment (armanbilge) [reply core/shared/src/main/scala/fs2/Stream.scala:1476]: Thanks for that explanation!

> `Int.MaxValue` is to account for the worst case scenario: at most the `chunkSize` parameter will be equal to `Int.MaxValue`

So could we just use `chunkSize` here, instead of `Int.MaxValue` ?

File: core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala (hunk 3 above)
Comment (Angel-O) [reply core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala:877]: it's because if the test fails we get a slightly better error message

```java.util.concurrent.TimeoutException: 7500 milliseconds``` which can be easily associated to `downstreamTimeout`

otherwise we get this value on the diff which looks a bit random

```_1 = 86405500000000 nanoseconds,```

but I'm happy to remove it

Comment (armanbilge) [reply core/shared/src/test/scala/fs2/StreamCombinatorsSuite.scala:877]: Got it, that is a nicer error :) thanks!

File: core/shared/src/main/scala/fs2/Stream.scala (hunk 4 above)
Comment (Angel-O) [reply core/shared/src/main/scala/fs2/Stream.scala:1476]: @armanbilge apologies I was wrong, that's not what's happening here. I'm just doing some tests to figure out why we need the additional `outputLong`

Comment (armanbilge) [reply core/shared/src/main/scala/fs2/Stream.scala:1476]: Btw, if these implementations details are no longer relevant after your rewrite in the other PR, then let's not get too hung up on this one :)

Comment (Angel-O) [reply core/shared/src/main/scala/fs2/Stream.scala:1476]: ok I think I've figured it out (might be useful for the other implementation actually)

basically the problem is that we need enough supply to cover 2 iterations of the race loop. So if we only increase it by `Int.MaxValue` the following will happen

- (current iteration): supply is unblocked
- (next iteration): supply gets stuck (not enough supply because upstream was interrupted)

in instead we increase it by `Int.MaxValue + outputLong`

- (current iteration): supply is unblocked
- (next iteration): supply is not blocked thanks to the additional `outputLong`

So since the chunkSize can be as high as `Int.MaxValue` then the minimum supply to unblock the semaphore should be `Int.MaxValue + outputLong`

Comment (armanbilge) [reply core/shared/src/main/scala/fs2/Stream.scala:1476]: > So since the chunkSize can be as high as `Int.MaxValue` then the minimum supply to unblock the semaphore should be `Int.MaxValue + outputLong`

Key word being "can". Wouldn't `chunkSize + outputLong` be sufficient?

**Comment by He-Pin** [comment]
Have you stress the latency of many fs streams with groupWithin？

File: core/shared/src/main/scala/fs2/Stream.scala (hunk 4 above)
Comment (Angel-O) [reply core/shared/src/main/scala/fs2/Stream.scala:1476]: yeah that should work. The test still passes, I'll change it to `outputLong * 2` since chunkSize == outputLong

**Comment by Angel-O** [comment]
> Have you stress the latency of many fs streams with groupWithin？

Hey @He-Pin , may I ask ? what do you mean exactly? Running many streams concurrently and using `groupWithin` on the resulting stream ? i.e. after calling `.parJoinUnbounded` ?

**Comment by He-Pin** [comment]
> > Have you stress the latency of many fs streams with groupWithin？
> 
> Hey @He-Pin , may I ask ? what do you mean exactly? Running many streams concurrently and using `groupWithin` on the resulting stream ? i.e. after calling `.parJoinUnbounded` ?

Eg, usging groupwithin to build a lock-step game server where the latency matters

**Comment by Angel-O** [comment]
> Eg, using groupwithin to build a lock-step game server where the latency matters

Thanks for the clarification. I must admit that unfortunately I've never heard of a lock-step server, so I haven't done any work (or rather wrote any test) with this particular use case in mind. Also keep in mind that I'm fairly new to open source contributions so maybe this is  more of a question for regular maintainers. 

Nonetheless, I'd be interested to find out more: can you point me towards an example or a beginner friendly resource? Thank you 🙏🏾

**Comment by armanbilge** [comment]
@He-Pin you are welcome to contribute some benchmarks for your usecase, that will probably be the best way to answer your question :)

**Comment by He-Pin** [comment]
> > Eg, using groupwithin to build a lock-step game server where the latency matters
> 
> Thanks for the clarification. I must admit that unfortunately I've never heard of a lock-step server, so I haven't done any work (or rather wrote any test) with this particular use case in mind. Also keep in mind that I'm fairly new to open source contributions so maybe this is  more of a question for regular maintainers. 
> 
> Nonetheless, I'd be interested to find out more: can you point me towards an example or a beginner friendly resource? Thank you 🙏🏾 

keep performance in mind, this is the way,mandalorian.

**Comment by He-Pin** [comment]
> @He-Pin you are welcome to contribute some benchmarks for your usecase, that will probably be the best way to answer your question :)

that's true, for my usecase i need to use a Hashed timer instead.

I'm learning more CE code too, will pr later.

**Review by armanbilge — APPROVED** [review]
Thanks for chasing this one down! The new tests specifying the expected behavior are great 👍
