### PR TITLE
Reimplement PipedInput/OutputStream

### LINKED ISSUE #2037: readOutputStream binds the OutputStream to the writing thread's lifetime
Consider this stream (FS2 2.4.4):
```scala
readOutputStream(blocker, 1024) { os =>
  blocker.delay[IO, Unit] {
    val t = new Thread(
      () => os.write(123)
    )
    t.start
    t.join
    Thread.sleep(1000)
  }
}
```
When run (OpenJDK 11), it produces this exception:
```
java.io.IOException: Write end dead
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:310)
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:377)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at fs2.io.package$.$anonfun$readBytesFromInputStream$1(io.scala:77)
...
```
This is caused by an absolutely ridiculous `PipedInputStream` gotcha - it throws an error if the last `Thread` to write to the `PipedOutputStream` has completed without closing the stream! This is a 20 year old [wontfix](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-4028322). :facepalm: 

Tying the `OutputStream` to a particular thread is extremely confusing, even more so in the Cats/FS2 context. We should fix this - or at the very least add a warning to the documentation and to the scaladoc.

### PR DESCRIPTION
**Pull request by vasilmkd**
Resolves #2037. I included the original reproduction as a test.

This was not pleasant to write.

### CODE REVIEW

**Comment by vasilmkd** [comment]
The failing tests are already solved by #2373.

File: io/src/main/scala/fs2/io/internal/InputOutputBuffer.scala [hunk 1]
```diff
@@ -0,0 +1,277 @@
...
+ */
+
+package fs2.io.internal
+
+import java.io.{InputStream, OutputStream}
+import java.util.concurrent.Semaphore
+
+/** Thread safe circular byte buffer which connects a [[java.io.OutputStream]]
+  * to a [[java.io.OutputStream]] in a memory efficient manner, without copying
+  * bytes unnecessarily.
```
Comment (diesalbla) [inline io/src/main/scala/fs2/io/internal/InputOutputBuffer.scala:29]: Would one of this actually be an _input_ stream?

Comment (vasilmkd) [reply io/src/main/scala/fs2/io/internal/InputOutputBuffer.scala]: You're right, good catch! 😆
Fixed.

File: io/src/main/scala/fs2/io/internal/InputOutputBuffer.scala [hunk 2]
```diff
@@ -0,0 +1,277 @@
...
+  *
+  * This is, in spirit, a clean room reimplementation of the
+  * [[java.io.PipedInputStream]] and [[java.io.PipedOutputStream]] pair of
+  * classes which can be used to achieve similar functionality, without the
+  * thread bookkeeping which is confusing in a multi threaded environment like
+  * the effect systems in which this code runs.
+  *
+  * @param capacity the capacity of the allocated circular buffer
+  */
+private[io] final class InputOutputBuffer(private[this] val capacity: Int) { self =>
```
Comment (diesalbla) [inline io/src/main/scala/fs2/io/internal/InputOutputBuffer.scala:44]: One general question: given that this entire class only depends on Java libraries, could it be submitted for the Scala standard library? Sys or process.

File: io/src/main/scala/fs2/io/internal/InputOutputBuffer.scala [hunk 3]
```diff
@@ -0,0 +1,277 @@
...
+
+  private[this] val buffer: Array[Byte] = new Array(capacity)
+
+  private[this] var head: Int = 0
+  private[this] var tail: Int = 0
+
+  private[this] var closed: Boolean = false
+
+  private[this] val readerPermit: Semaphore = new Semaphore(1)
+  private[this] val writerPermit: Semaphore = new Semaphore(1)
```
Comment (mpilquist) [inline io/src/main/scala/fs2/io/internal/InputOutputBuffer.scala:54]: Could you add a summary of how these permits are used? Are their values every > 1?

Comment (vasilmkd) [reply io/src/main/scala/fs2/io/internal/InputOutputBuffer.scala:54]: I believe they can be, they are not completely foolproof, they are just here to prevent threads from looping endlessly when there is nothing to be read from the buffer. This is fine, because there is one more monitor, the `self.synchronized` block, which actually guards the critical section. Does this make any sense?

Comment (mpilquist) [reply io/src/main/scala/fs2/io/internal/InputOutputBuffer.scala:54]: Okay cool. My only concern is that some strange access pattern could result in `writerPermit` getting very large, which then causes lots of looping when waiting to write.

Comment (vasilmkd) [reply io/src/main/scala/fs2/io/internal/InputOutputBuffer.scala:54]: Ok, let's not rush this, I will reiterate on the code.

Comment (vasilmkd) [reply io/src/main/scala/fs2/io/internal/InputOutputBuffer.scala]: I implemented a custom synchronizer that allows at most 1 permit at any time.

**Comment by vasilmkd** [comment]
Wow the `AbstractQueuedSynchronizer` API is something else...

File: io/src/main/scala/fs2/io/internal/InputOutputBuffer.scala (hunk 3 above)
Comment (mpilquist) [reply io/src/main/scala/fs2/io/internal/InputOutputBuffer.scala]: Looks great!
